apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: polyshop-gateway-ingress
  namespace: polyshop
  labels:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/part-of: polyshop
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  rules:
    - host: polyshop.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gateway
                port:
                  number: 80
  tls:
    - hosts:
        - polyshop.local
      secretName: polyshop-tls
